name: CI

on: [push, pull_request]

jobs:
  CompileThesis:
    name: Compile thesis to PDF
    runs-on: ubuntu-18.04
    container: texlive/texlive:latest
    defaults:
      run:
        working-directory: ./thesis
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install \
            texlive-local \
            biber
      - name: Build
        run: arara "BP_Straka_David_2021"
      - name: Archive thesis PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: BP_Straka_David_2021.pdf
          path: thesis/BP_Straka_David_2021.pdf
      - name: Print compilation log
        if: always()
        run: |
          cat BP_Straka_David_2021.log
          ls -la
